services:
  sqlserver:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=safe-pass123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5673:15672"
      - "5672:5672"
    hostname: rmq
    environment:
      RABBITMQ_DEFAULT_USER: greybeast
      RABBITMQ_DEFAULT_PASS: string123
    volumes:
      - rabbit_data:/var/lib/rabbitmq
  api:
    image: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  webui:
    build:
      context: Web.UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

volumes:
  sql_data:
    driver: local
  rabbit_data:

#  mailserver:
#    image: rnwood/smtp4dev
#    container_name: mail-server
#    ports:
#      - "5000:80"
#      - "2525:25"
#
